name: Song Submission Discord Webhook

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - reopened
      - edited
      - ready_for_review
      - synchronize
      - closed
      - opened

jobs:
  send-webhook:
    permissions: write-all
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Post Discord Message
      run: node .github/scripts/python/pr_analyzer.py
      env:
        PR_NUMBER: ${{ github.event.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PAT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_SUBMISSIONS: ${{ secrets.DISCORD_WEBHOOK_SUBMISSIONS }}
        TRIGGERED_ACTION: ${{ github.event.action }}
