name: Pull Request Merge

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Append PR message to JSON
        run: node .github/scripts/append-json.js
        env:
          PR_NUMBER: ${{ github.event.number }}
          PAT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK_SUBMISSIONS: ${{ secrets.DISCORD_WEBHOOK_SUBMISSIONS }}
          DISCORD_WEBHOOK_PUBLICFILE: ${{ secrets.DISCORD_WEBHOOK_PUBLICFILE }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}

      - name: Create Zip
        run: |
          python3 zip_mapped.py
          zip -r -q binaries.zip binaries

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git add .
          git commit -m "Update JSON file with PR message for #${{ github.event.number }}"
          git push
