name: Bulk Merge PRs

on:
  workflow_dispatch:
    inputs:
      prnum:
        description: 'List of PR Numbers, delimited by a comma'
        required: true
        default: '0'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
        run: pip install -r requirements.txt

    - name: Run Merge Script
      run: python .github/scripts/python/append_json_multiple.py
      env:
        PR_NUMBER_LIST: "${{ github.event.inputs.prnum }}"
        GITHUB_REPOSITORY: ${{ github.repository }}
        PAT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_SUBMISSIONS: ${{ secrets.DISCORD_WEBHOOK_SUBMISSIONS }}
        DISCORD_WEBHOOK_PUBLICFILE: ${{ secrets.DISCORD_WEBHOOK_PUBLICFILE }}
        YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
        YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
    
    - name: Create Zip
      run: |
        python3 zip_mapped.py
        zip -r -q binaries.zip binaries

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        git add .
        git commit -m "Update JSON file with PR message for #${{ github.event.number }}"
        git push

